### ISSUE TITLE
which file is submitted to the server?

### ISSUE THREAD

**Issue by hugddygff** [JaywongWang/DenseVideoCaptioning#11]
I used  test.py to generate the max_proposal_1000 json file,  then used the evaluate.py to obtain meteor point. 

But the format of the max_proposal_1000 json file is a little different from the sample file. So which file is submitted to the server?

Thanks.

**Comment by JaywongWang** [comment]
Here is the file I submitted: https://drive.google.com/open?id=10CkQAhl8xkFNh5HTyGoFp7KEkZoS5EEU .
If you run test.py for submission, please change split = 'test' (not 'val') at Line 96.

**Comment by JaywongWang** [comment]
Solved.
