### ISSUE TITLE
Options not clear in opt.py

### ISSUE THREAD

**Issue by noobiecoder1942** [JaywongWang/DenseVideoCaptioning#12]
What exactly is the pipeline to be followed for training?
1. for pre-training proposal module:
`options['init_module'] = 'proposal'  # all/proposal/caption, which module to initialize`
`options['train_proposal'] = True   # whether to train variables of proposal module`
`options['train_caption'] = False    # whether to train variables of captioning module`
2. What should be the values for the above parameters for complete model training?
3. Also, when training the complete model, should the proposal model checkpoint be used at `options['init_from']`?

**Comment by JaywongWang** [comment]
The whole pipeline should be: 
1) Train a proposal model: options['init_module']='proposal', options['init_from']='', options['train_proposal']=True, options['train_caption']=False;  
2) Train the complete model: options['init_module']='proposal', options['init_from'] = [path_to_the_above_trained_proposal_model], options['train_proposal']=True, options['train_caption']=True

Note that my implementation only supports batch_size=1. To achieve better proposal performance, you may consider modify the code to support batch_size=32 (or higher) to train a better proposal module.
