### ISSUE TITLE
Working demo

### ISSUE THREAD

**Issue by leenaraz** [JaywongWang/DenseVideoCaptioning#13]
How to use the model to caption a single video? 
Thankyou

**Comment by gauravrana100** [comment]
I am not completely sure about the answer, but point out if it's wrong.
If you want to caption a single video from the test data which is provided just remove other ID's.
But if you want to get you own video to test for the current model, you'll need the C3D features which were already provided by the author. C3D in keras is already available online. It will be a lengthy process as you'll have to download all the data and then do the pre-processing explained, finally doing the transform on the test video.

**Comment by bassemhossam** [comment]
I have already tried to extract c3d features from 'fc7' and then perform pca on them to reduce the dimensions from 4096 to 500 ,but i am producing very different features on the same video in comparison to the author's provided features so i must be doing something wrong and i was wondering if anyone have any detailed steps or instructions for me to follow to try to recreate the feature extraction .

**Comment by JaywongWang** [comment]
I am not sure about what caused such inconsistency. You may find the PCA description here http://activity-net.org/challenges/2016/download.html#c3d, to see if any help.

**Comment by gauravrana100** [comment]
Thank you

Gaurav Rana
