### ISSUE TITLE
Trying to run the model on a single video 

### ISSUE THREAD

**Issue by bassemhossam** [JaywongWang/DenseVideoCaptioning#14]
I have already tried to extract c3d features from 'fc7' and then perform pca on them to reduce the dimensions from 4096 to 500 ,but on the same video from the dataset i am producing very different features  in comparison to the author's provided features so i must be doing something wrong and i was wondering if anyone have any detailed steps or instructions for me to follow to try to recreate the feature extraction .

**Comment by supun-kanda** [comment]
ActivityNet has provided the PCA to the first 500 components, and sports1m weights can be found on internet. 

> for any video, fc7 provides 4096 feature layer. If 1 stride considered, by multiplying by PCA first 500, we should be able to get dimension reduced c3d features. But as you say, the features are different.   

There should be something wrong with above process, or otherwise it should be weights.

**Comment by JaywongWang** [comment]
I am not sure about what caused such inconsistency. You may find the PCA description here http://activity-net.org/challenges/2016/download.html#c3d, to see if any help.

**Comment by bassemhossam** [comment]
Thank for the help i was able to solve the problem.

**Comment by supun-kanda** [comment]
@bassemhossam  can you explain what was the solution
