### ISSUE TITLE
ActivityNet Captions Dataset

### ISSUE THREAD

**Issue by nayyeraafaq** [JaywongWang/DenseVideoCaptioning#15]
Where can we download the Activity_Net Captions dataset videos. I am not asking for C3D features.

**Comment by JaywongWang** [comment]
The videos from ActivityNet Captions dataset is the same as ActivityNet v1.3 dataset. Please download them from http://activity-net.org/download.html.

**Comment by JaywongWang** [comment]
Download ActivityNet v1-3 annotation json data. Then you can extract corresponding video urls from the annotation.

**Comment by nayyeraafaq** [comment]
Thanks JaywongWang. I have tried downloading from urls but few of the urls are not available. 
Does anyone have had the similar problems? Is it temp or permanent issue? Thats why I was wondering how to get complete dataset.

**Comment by JaywongWang** [comment]
It is a permanent issue. We also encountered similar problem when donwloading the videos. This is possibly because the Youtube users changed the accessibility of the videos.
