### ISSUE TITLE
coco API

### ISSUE THREAD

**Issue by Shanzaay** [JaywongWang/DenseVideoCaptioning#17]
Hi, can you explain to me a little how do I install cocoAPI? Because I am getting an error at the coco libraries.  And I can't seem to install the library either. 

Many Thanks

**Comment by JaywongWang** [comment]
I think there is no need to install any API. Please make sure you run the code in Python2.7x. The coco evaluation code only supports Python2.7x.

**Comment by Shanzaay** [comment]
coco evaluation code, you mean the file name eval.py or evaluate.py... or which one?

**Comment by Shanzaay** [comment]
does cocoAPI support by windows?

**Comment by JaywongWang** [comment]
All codes need to run in Python2.7x. The evaluate.py relies on /densevid_eval-master/coco-caption API. I think it does not need installation. Both Linux and Window are supported.

**Comment by Shanzaay** [comment]
Thanks @JaywongWang
