### ISSUE TITLE
IOError: Broken pipe when train the proposal

### ISSUE THREAD

**Issue by silverbulletmdc** [JaywongWang/DenseVideoCaptioning#2]
Hi, Jaywong:
I try to run your code in my computer, and I set the train_caption to False and train_proposal to True following your README.md. Then I run `python train.py`. But after some training processes, the program was crashed with following error message:
```
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(options)
  File "train.py", line 392, in train
    all_scores, combined_score = evaluation_metric_greedy(options, data_provision, sess, proposal_inputs, caption_inputs, proposal_outputs, caption_outputs)
  File "train.py", line 213, in evaluation_metric_greedy
    evaluator.evaluate()
  File "./densevid_eval-master/evaluator_efficient.py", line 110, in evaluate
    scores = self.evaluate_tiou(tiou)
  File "./densevid_eval-master/evaluator_efficient.py", line 268, in evaluate_tiou
    score, scores = scorer.compute_score(gts[vid_id], res[vid_id])
  File "./densevid_eval-master/coco-caption/pycocoevalcap/meteor/meteor.py", line 38, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "./densevid_eval-master/coco-caption/pycocoevalcap/meteor/meteor.py", line 57, in _stat
    self.meteor_p.stdin.write(str_mess.encode())
IOError: [Errno 32] Broken pipe
```

I think it is caused by the meteor wrapper.  I use openjdk version "1.8.0_181", python2.7.15. How can I fix it?

**Comment by silverbulletmdc** [comment]
I solved it by downloading meteor-1.5.jar to meteor folder. I think you should write it in the README.md.

**Comment by JaywongWang** [comment]
That's wired. Do you mean that my provided meteor-1.5.jar is broken or outdated? Can you download my provided meteor-1.5.jar again and repeat the experiment to see if the error still occurs?

**Comment by JaywongWang** [comment]
The evaluation folder (/densevid_eval-master/coco-caption) is actually from https://github.com/tylin/coco-caption/tree/3f0fe9b819c0ea881a56441e4de1146924a394eb

**Comment by silverbulletmdc** [comment]
I'm sorry. It's the 'meteor/data/paraphrase-en.gz' file which was missed. Not the `jar` file.

**Comment by gazal2708** [comment]
Hello , i am getting the same broken pipe error in the same line even though i have downloaded paraphrase-en.gz  in meteor/data/ folder
