### ISSUE TITLE
C3D feature extraction program

### ISSUE THREAD

**Issue by GauravKrRoy** [JaywongWang/DenseVideoCaptioning#20]
can u plz provide the code of c3d feature extraction. I need to see while creating hdf5 file how you are mapping video ids and corresponding features.
If I singly extract the video features using numpy and then merge all numpy files and give it as a feature file in train.py. Will it work?

**Comment by JaywongWang** [comment]
Please see dataset/ActivityNet_Captions/features/*.py

**Comment by GauravKrRoy** [comment]
I am using VGG16 for feature extraction and getting the feature of shape(4096,) for each video.
Can u please update dataset/ActivityNet_Captions/features/*.py so that it can output a feature of ( , , 500)

**Comment by JaywongWang** [comment]
You may check http://activity-net.org/challenges/2016/download.html#c3d and ask fabian.caba@kaust.edu.sa or victor.escorcia@kaust.edu.sa for more details about PCA processing. My code directly utilizes the PCA-processed features.
