### ISSUE TITLE
Hi, you can download it here: [https://drive.google.com/file/d/1D6-sDPEkOJX32h0-EclxpiEmiMkNGybo/view?usp=sharing](url)

### ISSUE THREAD

**Issue by GauravKrRoy** [JaywongWang/DenseVideoCaptioning#21]
Hi, you can download it here: [https://drive.google.com/file/d/1D6-sDPEkOJX32h0-EclxpiEmiMkNGybo/view?usp=sharing](url)

_Originally posted by @JaywongWang in https://github.com/JaywongWang/DenseVideoCaptioning/issues/1#issuecomment-427807540_

I am unable to download this feature file from above link and can u please tell me how this feature file is different from feature file used for  training i.e. activitynet_c3d_fc7_stride_64_frame.hdf5

**Comment by JaywongWang** [comment]
You may try https://drive.google.com/open?id=1UquwlUXibq-RERE8UO4_vSTf5IX67JhW .
The official C3D is in http://activity-net.org/challenges/2016/download.html#c3d . The features are with stride of 8 frames. In my paper, I directly downsample the features to stride of 64 frames (8-times) by mean pooling (a mean pooling layer with kernel=8 and stride=8). Please download the codes for generating h5 file in my updated repo.

**Comment by GauravKrRoy** [comment]
why you are using sub_activitynet_v1-3_stride_64frame.c3d.hdf5 file to generate anchors and get their weights while you are using  activitynet_c3d_fc7_stride_64_frame.hdf5 for training. Are both the files same.

**Comment by JaywongWang** [comment]
They are the same. I accidentally renamed the file.

**Comment by KPKWCE** [comment]
Hi  
GauravKrRoy,

I am trying to execute test.py but getting the following error.

Restoring model from
ValueError Traceback (most recent call last)
in
3 tf.reset_default_graph()
4 options = default_options()
----> 5 test(options)

in test(options)
20 print('Restoring model from %s'%options['init_from'])
21 saver = tf.train.Saver()
---> 22 saver.restore(sess, options['init_from'])
23
24 word2ix = options['vocab']

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py in restore(self, sess, save_path)
1280 if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
1281 raise ValueError("The passed save_path is not a valid checkpoint: " +
-> 1282 checkpoint_prefix)
1283
1284 logging.info("Restoring parameters from %s", checkpoint_prefix)

ValueError: The passed save_path is not a valid checkpoint:

Could you please help me on these issues?
Thanks for your time and great work!
