### ISSUE TITLE
In subprocess.py OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by youngboy52** [JaywongWang/DenseVideoCaptioning#22]
When I start to train the model through the script train.py, there is an OS error happened as follows:
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    train(options)
  File "train.py", line 396, in train
    all_scores, combined_score = evaluation_metric_greedy(options, data_provision, sess, proposal_inputs, caption_inputs, proposal_outputs, caption_outputs)
  File "train.py", line 217, in evaluation_metric_greedy
    verbose=False)
  File "./densevid_eval-master/evaluator_old.py", line 61, in __init__
    self.scorers = [(Meteor(), "METEOR")]
  File "./densevid_eval-master/coco-caption/pycocoevalcap/meteor/meteor.py", line 25, in __init__
    bufsize=0)
  File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
I constructed an environment to implement my tensorflow. This issue has plenty of solutions online, however, they can not deal with my problem. Does someone have the same experience?

**Comment by Shanzaay** [comment]
Hi Jaywong. When I try to run .train.py I am getting this following error: 
even though the path is correct. Any suggestion what could be the problem be. I try in online but the solution there is no help as I already tried them all.  

OSError: Unable to open file (unable to open file: name = 'E:/DenseVideoCaptioning-master/dataset/ActivityNet/features/activitynet_c3d_fc7_stride_64_frame.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by Shanzaay** [comment]
Seem like it couldn't locate meteor.py file...  are you sure the file is located there?  If so for that i install cocoapi.... I am not sure if it'll work for your case.

**Comment by JaywongWang** [comment]
@youngboy52 I guess it is possibly due to the missing of the file https://github.com/tylin/coco-caption/tree/3f0fe9b819c0ea881a56441e4de1146924a394eb/pycocoevalcap/meteor/data. Please follow the README.md and put it to the right place.

**Comment by nayyeraafaq** [comment]
I have the same error as @youngboy52. The meteor.py and downloaded file (paraphrase-en.gz) is also in place as mentioned in README.md. Any idea what is the issue ? @youngboy52  did you solve the issue ? Anyone else please share if you know the solution.

**Comment by 14080121** [comment]
> I have the same error as @youngboy52. The meteor.py and downloaded file (paraphrase-en.gz) is also in place as mentioned in README.md. Any idea what is the issue ? @youngboy52 did you solve the issue ? Anyone else please share if you know the solution.

Hi, do you solve the problem? I have the same problem in test.py. Can you share the solution with me?

**Comment by KPKWCE** [comment]
> When I start to train the model through the script train.py, there is an OS error happened as follows:
> Traceback (most recent call last):
> File "train.py", line 541, in
> train(options)
> File "train.py", line 396, in train
> all_scores, combined_score = evaluation_metric_greedy(options, data_provision, sess, proposal_inputs, caption_inputs, proposal_outputs, caption_outputs)
> File "train.py", line 217, in evaluation_metric_greedy
> verbose=False)
> File "./densevid_eval-master/evaluator_old.py", line 61, in **init**
> self.scorers = [(Meteor(), "METEOR")]
> File "./densevid_eval-master/coco-caption/pycocoevalcap/meteor/meteor.py", line 25, in **init**
> bufsize=0)
> File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> I constructed an environment to implement my tensorflow. This issue has plenty of solutions online, however, they can not deal with my problem. Does someone have the same experience?

Hello, I have also the same experience, have solved this error?

**Comment by KPKWCE** [comment]
@youngboy52 @nayyeraafaq @JaywongWang @Shanzaay Have you got the solution pls share

**Comment by Shanzaay** [comment]
No i wasn't.
