### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Shanzaay** [JaywongWang/DenseVideoCaptioning#23]
Hi Jaywang.... I am getting this following index error.  I can't seem to solve it. Help me out here, please. Or is it because of the "while true loop"....

E:\jupyter book\data_provider.py in iterate_batch(self, split, batch_size)
    160             vid = ids[i+current]
    161             feature_fw = self._features[vid]
--> 162             feature_len = feature_fw.shape[0]
    163 
    164 

IndexError: tuple index out of range

###############################################################
# provide batch data
    def iterate_batch(self, split, batch_size):

        ids = list(self._ids[split])

        if split == 'train':
            print('Randomly shuffle training data ...')
            random.shuffle(ids)

        current = 0
        
        
        while True:

            batch_paragraph = []
            batch_feature_fw = []
            batch_feature_bw = []
            batch_proposal_fw = []
            batch_proposal_bw = []

            # train in pair, use one caption as common gt
            batch_proposal_caption_fw = [] # 0/1 to indicate whether to select the lstm state to feed into captioning module (based on tIoU)
            batch_proposal_caption_bw = [] # index to select corresponding backward feature

            i = 0 # batch_size = 1
            vid = ids[i+current]
            feature_fw = self._features[vid]
            feature_len = feature_fw.shape[0]

**Comment by JaywongWang** [comment]
Please first make sure your code is up-to-date.

**Comment by Shanzaay** [comment]
What do you mean?

**Comment by Shanzaay** [comment]
Yes its up-to-date Jaywong...

**Comment by JaywongWang** [comment]
Normally, feature_fw is a numpy array. However, based on the error message, it seems to be a tuple. I suggest you printing out the features (both type and content) for debug purpose.

**Comment by JaywongWang** [comment]
It seems feature_fw.shape is an empty tuple.  This means that the input feature could be an empty array. Please check your input feature h5.

**Comment by Shanzaay** [comment]
oky i'll try and then let you know....

**Comment by Shanzaay** [comment]
well i did check it. input feature h5 is not empty.

**Comment by JaywongWang** [comment]
Have you used my privided features ? I also notice the line number of your code (e.g., 162) is different from the provided code. I guess you have modified the code. Please double check the difference.

**Comment by Shanzaay** [comment]
Yes i used your provided features. The lines are just changed because i add
few print statements nothing else. The code is the same.

**Comment by JaywongWang** [comment]
I just downloaded the repo and successfully re-trained the model without any error message. I guess you need more detailed debugging.

**Comment by JaywongWang** [comment]
I will test the C3D feature link again and I will let you know if any error message.

**Comment by JaywongWang** [comment]
Both the provided codes and the features are bug-free in my side.

**Comment by Shanzaay** [comment]
owky.. thanks a bunch... I will check again if there is something wrong
with my code.
