### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by youngboy52** [JaywongWang/DenseVideoCaptioning#25]
Traceback (most recent call last):
  File "test.py", line 328, in <module>
    evaluation(options, resFile)
  File "test.py", line 292, in evaluation
    evaluator.evaluate()
  File "./densevid_eval-master/evaluator.py", line 108, in evaluate
    scores = self.evaluate_tiou(tiou)
  File "./densevid_eval-master/evaluator.py", line 215, in evaluate_tiou
    tokenize_res = self.tokenizer.tokenize(cur_res)
  File "./densevid_eval-master/coco-caption/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/strong/anaconda2/envs/tensorflow/lib/python2.7/subprocess.py", line 938, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

I tried to run the script of test.py, but the error above happened. However, I had checked the memory status of my server, which is showed as follows:
              total        used        free      shared  buff/cache   available
Mem:          31939        4844       24682         280        2412       26400
Swap:          2047        1990          57
There were still lots of memory can be used. Is there something wrong with my python interpreter or anything else?   
What's more, can you provide the implementation of C3D project which you use? The related url is ok.

**Comment by JaywongWang** [comment]
The evaluation code requires enough memory.  After the memory error occurs, the occupied memory has been released. So you won't be able to check the original memory status.

**Comment by JaywongWang** [comment]
The C3D features were directly downloaded from the website. Please follow the README.md.

**Comment by youngboy52** [comment]
Thank you for your help! However, I want to extract the C3D features of my own personal videos. To assert the unified form of feature distribution, I need to know the C3D feature extractor which you use. You maybe directly use the downloaded features from the website where there are no details about the feature extractor (Which dataset is used to train it, Sport1M or UCF 101 dataset ? Where we can download it?). If you know something about it, could you tell me?

**Comment by JaywongWang** [comment]
The C3D features were pre-trained on Sports-1M.  The ActivityNet website (http://activity-net.org/challenges/2016/download.html#c3d) further did PCA processing to obtain 500-d features. For a new video, please first extract C3D features following https://github.com/facebook/C3D (or other codes in github) and perform PCA.
