### ISSUE TITLE
Error loading pre-trained model

### ISSUE THREAD

**Issue by aurooj** [JaywongWang/DenseVideoCaptioning#27]
Hi, I am attempting to run test.py using your pre-trained model. It throws me the following error when loading model:
W tensorflow/core/framework/op_kernel.cc:993] Not found: Tensor name "caption_module/multi_rnn_cell/cell_0/lstm_cell/weights" not found in checkpoint files checkpoints/model.ckpt
	 [[Node: save/RestoreV2_11 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_11/tensor_names, save/RestoreV2_11/shape_and_slices)]]

on the following line:
saver.restore(sess, options['init_from'])

Any help will be highly appreciated.

**Comment by JaywongWang** [comment]
Which version of tensorflow did you run on ?

**Comment by aurooj** [comment]
It's tensorflow-gpu 1.0.1.

**Comment by aurooj** [comment]
here is the detailed error:
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "proposal_module/video_encoder_fw/rnn/lstm_cell/weights" not found in checkpoint files checkpoints/model.ckpt
	 [[Node: save/RestoreV2_24 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_24/tensor_names, save/RestoreV2_24/shape_and_slices)]]
	 [[Node: save/RestoreV2_7/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_214_save/RestoreV2_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by aurooj** [comment]
For anyone who faces similar issue as mine, upgrading tensorflow version to 1.7 resolved the issue for me.
