### ISSUE TITLE
The process for feature extraction not clear

### ISSUE THREAD

**Issue by llafcode** [JaywongWang/DenseVideoCaptioning#29]
Hi,
I want to use your model to generate video captions for my own videos, and I would like to make clear the output dimension of the video features you used. Since you didn't provide any code for feature extraction, I followed your links in this repo and eventually found [this](https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor) for C3D feature extraction. Please correct me if I used a wrong one. In the later description of my question I would assume this is a correct implementation for C3D feature extraction.

If I understand correctly, you first extract features every 16 frames for a given input video, obtaining a long feature vector and then apply PCA to that vector to reduce its dimensionality to 500. 

Lets say, for example, I have a video with 50 frames:
1. By running the c3d feature extractor I posted before, I got a (3, 4096) dimension feature matrix. This first dimension is 3 because there are 3 chunks of 16-frame in the 50 frames video, and the rest 2 frames are discarded. 
2. To apply PCA to the obtained C3D features, should I expect a (3, 500) or (500, ) output dimension? It's really not clear according to all the guidances you provided in this repo. I'm sorry if this is a silly question but I'm quite new to this field. About the PCA, I have read all the closed issues and found that you said in #26, 
> PCA_activitynet_v1-3.hdf5 provides information needed to perform PCA on new data points (standardization, projection, etc.).

but I have no idea how to use this file (I suppose the hdf5 file contains the features after PCA, how can it help me to produce my own video features?), could you please kindly provide any hint for this step?

Thank you very much for your help in advance.

**Comment by JaywongWang** [comment]
For me, it's pretty easy to obtain features from ActivityNet, as the 500-d PCA-processed features can be directly downloaded from the ActivityNet website. As I am not sure what is the exact process, I suggest you contact with the ActivityNet organizers (http://activity-net.org/challenges/2019/contact.html).

**Comment by llafcode** [comment]
Thank you very much.
