### ISSUE TITLE
Tank you for your work.look forword to your answer

### ISSUE THREAD

**Issue by a1391651300** [JaywongWang/DenseVideoCaptioning#30]
Thank you a lot for your work. Is the Pre-trained Model has been well trained ?Could I  inference the  video of the activate dataset using it without any extra training?  
Should I get the C3D features and PCA the features into 500 dims ,If I want to inference my video?

                                                                                                thank you ,look forword to your answer

**Comment by JaywongWang** [comment]
The provided model was well trained on ActivityNet-Captions dataset. You may try generating captions for your own videos. The input features should be first processed into 500-d. You may follow https://github.com/JaywongWang/DenseVideoCaptioning/issues/26 .

**Comment by a1391651300** [comment]
Thank you very  much for your answer timely.I have red the #26.Now I am trying to get C3D features first. Then processed the features to 500-d by the code  as following. Do you think the code of pca  has well implemented the idea of #26?     Tank you a lot ,and I will close the question soon.  

class PCA(object):
    def __init__(self, file_name):
        pca = h5py.File(file_name, 'r')
        self.U = pca['data']['U'].value
        self.S = pca['data']['S'].value
        self.x_mean = pca['data']['x_mean'].value

    def transform(self, X, dim):
        if X.shape[1] != self.x_mean.shape[1]:
            raise Exception("Not equal dimension")
        X = X - self.x_mean
        Um = self.U[:dim, :]
        out = np.matmul(X, Um.transpose(1, 0))
        return out

**Comment by JaywongWang** [comment]
I think "out = np.matmul(X, Um.transpose(1, 0))" should be changed to "out = np.matmul(Um.transpose(1, 0), X)", because the eigen-vectors are saved colume-wise in Um.

**Comment by a1391651300** [comment]
Thank you for your answer.I am so sorry to bother you again.The dim is not right if I change the code as you told to me
[ValueError: shapes (4096,500) and (205,4096) not aligned: 500 (dim 1) != 205 (dim 0)]
Do you mean I should change like this 
    Um = self.U[:, :dim]
    out = np.matmul(X, Um)  
    ###dim ==500
Could you please give me some inspiration? It will be best ,if you have some projects on getting the c3d features and pca .Thank you

**Comment by JaywongWang** [comment]
Let us define some notations first:
1. X: in shape of [n_feature, 4096], where there are n_feature features extracted from a video
2. U: eigen-vectors, each colum representing one eigen-vector. The PCA data provides 4096*4096 full data, we need to extract the top-500 eigen-vectors.

The codes should be:

def transform(self, X, dim):
    if X.shape[1] != self.x_mean.shape[1]:
        raise Exception("Not equal dimension")
    X = X - self.x_mean
    Um = self.U[:, :dim]
    out = np.matmul(X, Um)  # equivalent to out = np.matmul(Um.transpose(1, 0), X.transpose(1, 0)).transpose(1, 0)
    return out

**Comment by JaywongWang** [comment]
> Thank you for your answer.I am so sorry to bother you again.The dim is not right if I change the code as you told to me
> [ValueError: shapes (4096,500) and (205,4096) not aligned: 500 (dim 1) != 205 (dim 0)]
> Do you mean I should change like this
> Um = self.U[:, :dim]
> out = np.matmul(X, Um)
> ###dim ==500
> Could you please give me some inspiration? It will be best ,if you have some projects on getting the c3d features and pca .Thank you

Yes, I think you should change like that.

**Comment by a1391651300** [comment]
Thank you so much.The  effect has been improved by the way you told me.  I also found the frame features are usually extracted just like [1:16] [8:24] ....16 frames for each batch and the stride is 8(每16帧提一个3D特征，步长为8).So amazing .Finally,thank you for you help so much.

**Comment by 14080121** [comment]
> Thank you so much.The effect has been improved by the way you told me. I also found the frame features are usually extracted just like [1:16] [8:24] ....16 frames for each batch and the stride is 8(每16帧提一个3D特征，步长为8).So amazing .Finally,thank you for you help so much.

I ran your above code without response, could you provide your PCA code, and did you first convert the feature to numpy file, and did you use PCA_activitynet_v1-3.hdf5？Looking forward to your reply！

**Comment by JaywongWang** [comment]
Hi:


Our code directly uses the PCA-processed features (500-dim). So I have no PCA code and I don't need PCA_activitynet_v1-3.hdf5.
Our code directly loads the whole .hdf5 feature file (including all video features). Therefore, it takes some time and requires enough CPU and GPU memory.






Sincerely,
Jingwen Wang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"14080121"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 上午10:22
收件人:&nbsp;"JaywongWang/DenseVideoCaptioning"<DenseVideoCaptioning@noreply.github.com&gt;;
抄送:&nbsp;"天外来客"<525021930@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JaywongWang/DenseVideoCaptioning] Tank you for your work.look forword to your answer (#30)



 
Thank you so much.The effect has been improved by the way you told me. I also found the frame features are usually extracted just like [1:16] [8:24] ....16 frames for each batch and the stride is 8(每16帧提一个3D特征，步长为8).So amazing .Finally,thank you for you help so much.
  
I ran your above code without response, could you provide your PCA code, and did you first convert the feature to numpy file, and did you use PCA_activitynet_v1-3.hdf5？Looking forward to your reply！
