### ISSUE TITLE
c3d feature

### ISSUE THREAD

**Issue by BMEI1314** [JaywongWang/DenseVideoCaptioning#31]
如果要跑实时视频,缺少提c3d的模型，官网没找到,有开源吗.

**Comment by a1391651300** [comment]
我之前遇到过这个问题，c3d特征提取链接是https://github.com/facebookarchive/C3D/tree/master/C3D-v1.0/examples/c3d_feature_extraction。这个是官方发布的应该是最准的。pca代码在这个回答下边#30 下边。里边有我和作者的讨论。
