### ISSUE TITLE
There is something wrong happened

### ISSUE THREAD

**Issue by a1391651300** [JaywongWang/DenseVideoCaptioning#32]
Thank you for your help.Now I am able to get the C3D feature from link  https://github.com/facebookarchive/C3D/tree/master/C3D-v1.0/examples/c3d_feature_extraction. 
And I dim to 500 with the way of PCA that you told me .But the results of my own videos is not very satisfactory. 好吧，我推测您也是中国的同学，那么我用汉语描述下边的问题可能更方便些。现在我整个流程可以跑通，但是预测我自己视频的时候会出现一些不准确的问题。例如会把一些视频上的彩色字幕预测为口风琴，会把足球预测为曲棍球，大概率会出现“the man speak to the camera”。我不知道这种现象是不是我的一些不当操作造成的，比如特征提的不准确。我的视频长度通常是2min左右。非常期待您的回答。

**Comment by JaywongWang** [comment]
这是正常的。模型的能力受限于ActivityNet数据集的bias，比如数据集里面经常出现的一句话就是“the man speak to the camera”。识别错误的问题，可能受限于特征的表征能力以及模型的建模能力。看起来也是正常的结果。
