### ISSUE TITLE
Applying PCA on Features extracted

### ISSUE THREAD

**Issue by aliakber366** [JaywongWang/DenseVideoCaptioning#34]
Can you please guide or suggest a suitable repository which guides on how to calculate PCA after we have extracted features from (1,6,4096) to (1,6,500)? 

I tried several methods but was facing issues so it would be great if you could guide in this matter.

Looking forward to hearing from you soon and thanking you in advance.

**Comment by JaywongWang** [comment]
I think you may find solution in https://github.com/JaywongWang/DenseVideoCaptioning/issues/26 .

**Comment by aliakber366** [comment]
Thank you very much sir. Indeed, I followed the steps and applied PCA and fed to the model, however, I am not receiving satisfactory results for some reason. I also tried to evaluate my method of computation using one of the videos in the validation dataset, however, I am unable to produce the correct steps.

I am writing the steps I followed and would be very grateful if you could verify and suggest 

1) Extracted features and applied PCA as given in https://github.com/supun-kanda/FYP/blob/master/c3d-keras/pca.py

3) Converted .npy file to hdf5 using the get_c3d_h5.py file given in your project.

I would be very thankful to you if you could guide in this matter. 

Best regards.

**Comment by JaywongWang** [comment]
If you directly use my trained model for inference, you should use the ActivityNet-provided PCA means and variances: http://ec2-52-25-205-214.us-west-2.compute.amazonaws.com/data/challenge16/features/c3d/PCA_activitynet_v1-3.hdf5, even when you test a new video.

**Comment by aliakber366** [comment]
Thank you very much sir, however, can you please answer the below questions:

1) I tried extracting features using 2 methods: i) https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor, and, ii) Using https://github.com/supun-kanda/FYP/blob/master/c3d-keras/pca.py

Are these methods fine to extract the features for this use?

2) If the above methods are not fine, I tried using https://github.com/facebookarchive/C3D/tree/master/C3D-v1.0/examples/c3d_feature_extraction to extract features but was getting errors while using this and using Caffe. Can you please let me know how to use this repository's method to extract features?

**Comment by JaywongWang** [comment]
As for the details about feature extraction, I believe it is better to ask for help from http://activity-net.org/challenges/2017/contacus.html (e.g., ask for the codes for feature extraction). I am not sure if there is some other preprocessing on the website-provided features (http://activity-net.org/challenges/2017/download.html#c3d).

**Comment by aliakber366** [comment]
Sure sir, thank you very much. Sorry for disturbing again but I have another question:

About your referenced file of PCA from Activity Net, when I opened the file, I have S, U, x_mean and n_samples and then I have the extracted 4096 features.

Can you please explain what exactly do I need to do with these values to reduce the dimension to 500 features?

Thanking you once again for your kind cooperation.

**Comment by JaywongWang** [comment]
I think you can follow the code from "aukhan": https://github.com/JaywongWang/DenseVideoCaptioning/issues/26#issuecomment-542428970

**Comment by aliakber366** [comment]
Great, thank you very much sir for all your support throughout. 

Best regards
