### ISSUE TITLE
There are some problems about sentence_confidence

### ISSUE THREAD

**Issue by 14080121** [JaywongWang/DenseVideoCaptioning#35]
您好，我想问一下我跑出来的sentence confidence结果都是负的，这是正常情况么，为什么会出现负数呢，我刚接触这方面，还希望您指点一下，谢谢

**Comment by JaywongWang** [comment]
是正常的 有因为logP是负数（Pi最大值是1） 所以求和之后还是负数 最后的结果越接近0表示置信度越高
