### ISSUE TITLE
encounter some problems on train.py

### ISSUE THREAD

**Issue by TakeatEasy** [JaywongWang/DenseVideoCaptioning#36]
The error is as followed ，did i miss any step？
********** Tensor Shape ************
video_feat_fw: 
(?, ?, 500)
video_feat_bw: 
(?, ?, 500)
proposal_fw: 
(?, ?, 120)
proposal_bw: 
(?, ?, 120)
proposal_weight: 
(120, 2)
Evaluating the initialized model ...
vid: v_uqiMw7tQ1Cc
feature_len: 26
Evaluating batch: #0
Traceback (most recent call last):
  File "E:/pythonCode/DenseVideoCaptioning-master/train.py", line 547, in <module>
    train(options)
  File "E:/pythonCode/DenseVideoCaptioning-master/train.py", line 392, in train
    val_loss, val_proposal_loss, val_caption_loss = evaluation(options, data_provision, sess, inputs, t_loss_list)
  File "E:/pythonCode/DenseVideoCaptioning-master/train.py", line 49, in evaluation
    feed_dict=feed_dict[0:120][:])
TypeError: unhashable type

**Comment by JaywongWang** [comment]
This line of code: feed_dict=feed_dict[0:120][:]) is not the original code. Have you modified the code? "feed_dict" is a dictionary type. Please double check your modification.

**Comment by TakeatEasy** [comment]
Thanks for your timely reply
