### ISSUE TITLE
Can I use your model for generating timestamps for possible event segments?

### ISSUE THREAD

**Issue by DesaleF** [JaywongWang/DenseVideoCaptioning#39]
I want to generate timestamp for possible events in a video. How can I use your model only to generate timestamps for possible events in the video without generating the captions?

**Comment by 14080121** [comment]
have you save this question? I want to do this too.

**Comment by DesaleF** [comment]
Nope,  but I use different repo to do what I want. 
https://github.com/Pilhyeon/WTAL-Uncertainty-Modeling
but you need to extract the feature with different repository, which is tiresome. 
feature extractor: https://github.com/Finspire13/pytorch-i3d-feature-extraction
may be if you wanna help with these repos I can help you. but I was not able to modify this codebase.
