### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by ycbilge** [JaywongWang/DenseVideoCaptioning#8]
Hi Dear Jingwen,
Thank you for the code. 
I tried to run _test.py_ with the features you are referring  https://drive.google.com/file/d/1D6-sDPEkOJX32h0-EclxpiEmiMkNGybo/view?usp=sharing. However in this very part : 
```
    for vid in test_ids:
        print('\nProcessed %d-th video: %s'%(count, vid))

        # video feature sequence 
        video_feat_fw = features[vid].['c3d_fc7_features'].value
```
The error says : `KeyError: "Unable to open object (object 'c3d_fc7_features' doesn't exist)"`. I am using  the file that you provided : 
`features = h5py.File('dataset/ActivityNet/features/sub_activitynet_v1-3_stride_64frame.c3d.hdf5', 'r')
`

Also, When I tried to run _train.py_ with option init_from (in order to fine-tune the pretrained model) : 
`options['init_from'] = './DenseVideoCaptioning/checkpoints/model.ckpt` there is an error says : 
`IOError: [Errno 2] No such file or directory: './checkpoints/status.json' 
`
I can't see status.json in your code folder. 

Could you please help me on these issues?
Thanks for your time and great work!

**Comment by JaywongWang** [comment]
Sorry for the mistakes. I corrected the error in train.py and re-uploaded the correct feature file (https://drive.google.com/file/d/1UquwlUXibq-RERE8UO4_vSTf5IX67JhW/view?usp=sharing). Please update accordingly.

**Comment by JaywongWang** [comment]
Solved.
